framework:
  messenger:
    failure_transport: failed
    
    default_bus: command.bus
    buses:
      command.bus:
        middleware:
          - validation
          - doctrine_transaction
      query.bus:
        middleware:
          - validation

    transports:
      async:
        dsn:  "%env(MESSENGER_TRANSPORT_DSN)%"
      failed:
        dsn: "doctrine://default?queue_name=failed"

    routing:
      'App\Item\Middleware\Message\Command\CreateItemCommand': async
      'App\Item\Middleware\Message\Command\UpdateItemCommand': async
      'App\Item\Middleware\Message\Command\DeleteItemCommand': async
      'App\Item\Middleware\Message\Query\ListItemQuery': async
      'App\Item\Middleware\Message\Query\FindItemQuery': async